services:
  valkey:
    image: valkey/valkey
    container_name: valkey_instance
    ports:
      - 6379:6379

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_instance
    ports:
      - 6333:6333
    volumes:
      - ./qdrant_data:/qdrant/storage