FROM node:24

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/server ./apps/server

RUN pnpm install
RUN bun run db:generate

EXPOSE 8080

CMD ["bun", "run", "start:backend"]